### ISSUE TITLE
Keychain.org Documentation empty page

### ISSUE THREAD

**Issue by Flaxscrip** [KeychainMDIP/kc-docs#14]
The keychain.org "Documentation" links to an empty page instead of the manual.

https://keychain.org/docs/CLI-user-manual/
![Screenshot 2024-05-06 at 15 27 21](https://github.com/KeychainMDIP/kc-docs/assets/7094976/042b4a01-18e5-4f73-9462-fb1e94e69e40)

**Comment by alexfornuto** [comment]
Will be resolved by #12

**Comment by alexfornuto** [comment]
Actually, this was resolved earlier by adding a small index to this path, but the build wasn't updated. Solved with b86b41decd5d30d348ecd7ded88898b0ad0c7e38
