### ISSUE TITLE
Site icon for keychain.org

### ISSUE THREAD

**Issue by Flaxscrip** [KeychainMDIP/kc-docs#16]
Current site icon for keychain.org is the default Docusaurus icon. Can we replace with our keychain logo?

**Comment by alexfornuto** [comment]
This should have been fixed in #8. I suspect cached assets are to blame, will try rebuilding without cache.

**Comment by alexfornuto** [comment]
Resolved by b86b41decd5d30d348ecd7ded88898b0ad0c7e38
